### ISSUE TITLE
Unable to build on Ubuntu 20.04 with fltk 1.3.4

### ISSUE THREAD

**Issue by shifters67** [robcfg/retrotools#4]
I  am trying to build this on Ubuntu 20.04 following the instructions on the git page. I have installed FLTK 1.3 and 1.3 Dev (1.34) fine from default Ubuntu repo.

When i run make in the build folders i am getting lots of build errors (some of which below!) - any ideas what I am doing wrong?

[ 0%] Built target getscmversion
Scanning dependencies of target MMBExplorer
[ 14%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBExplorer.cpp.o
[ 28%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBFile.cpp.o
[ 42%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBE_Commands.cpp.o
[ 57%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBE_Gui.cpp.o
[ 71%] Building CXX object CMakeFiles/MMBExplorer.dir/src/MMBE_Callbacks.cpp.o
In file included from /home/twri/Downloads/6.BBC/MMB/retrotools/mmbexplorer/src/MMBE_Callbacks.cpp:4:
/home/twri/Downloads/6.BBC/MMB/retrotools/mmbexplorer/src/MMBE_Callbacks.h:35:29: error: ‘bool ChooseFilename’ redeclared as different kind of entity
35 | bool ChooseFilename( std::vector<std::string>& fileNames, const std::string& filter, const std::string& preset, bool bSaveAsDialog, bool bDirectory = false );
| ^~~~~~
In file included from /home/twri/Downloads/6.BBC/MMB/retrotools/mmbexplorer/src/MMBE_Callbacks.cpp:4:
/home/twri/Downloads/6.BBC/MMB/retrotools/mmbexplorer/src/MMBE_Callbacks.h:34:8: note: previous declaration ‘bool ChooseFilename(std::string&, const string&, const string&, bool, bool)’
34 | bool ChooseFilename( std::string& fileName, const std::string& filter, const std::string& preset, bool bSaveAsDialog, bool bDirectory = false );
| ^~~~~~~~~~~~~~
/home/twri/Downloads/6.BBC/MMB/retrotools/mmbexplorer/src/MMBE_Callbacks.cpp:24:6: note: candidate expects 5 arguments, 4 provided

<-- snip -->

make[2]: *** [CMakeFiles/MMBExplorer.dir/build.make:115: CMakeFiles/MMBExplorer.dir/src/MMBE_Callbacks.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/MMBExplorer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by robcfg** [comment]
This issue was due to some missing include files, it should be solved now.

**Comment by robcfg** [comment]
It's been confirmed fixed on Stardot.org.uk.
